### ISSUE TITLE
Instant 클래스 도입

### ISSUE THREAD

**Issue by hwangdaesun** [Step3-kakao-tech-campus/Team14_BE#43]
현재, 카카오테크캠퍼스 3단계에서 저희 팀 Spark는 게시물의 날짜를 저장하는 데 LocalDateTime 자료형을 사용하고 있습니다.

```java
@Entity
@NoArgsConstructor(access = PROTECTED)
@Getter
public class Post {

  // Primary Key
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long postId; // 게시글 ID
	
	...
	
  @Column(nullable = false)
  private LocalDateTime createdAt; // 생성일

	}
```

저희 어플리케이션에서는 게시물의 생성일을 활용해 게시물을 나이를 구하여 이를 인기도에 반영하고 있습니다.

즉, 게시물의 생성일 데이터는 단순 생성일을 저장하는 기록성 데이터가 아니라 비즈니스 로직에 영향을 끼치는 데이터입니다.

**따라서, Post 엔티티의 createdAt 컬럼의 자료형은 LocalDateTime이 아니라, 정확한 시간을 비교할 수 있는 Instant 자료형을 사용해야합니다.**

더 자세한 설명
---

[Instant 클래스 도입에 관한 고찰](https://rasony.tistory.com/174)

**Comment by yuseonkim** [comment]
오 그렇군요.. 확인했습니다!!!

**Comment by GoBeromsu** [comment]
음 그러네,, 동의합니다 타임존도 고려해야겠네유

## 관련 레퍼런스
- [백엔드가 이정도는 해야 함 : 어플리케이션 레벨 의사 결정](https://velog.io/@city7310/%EB%B0%B1%EC%97%94%EB%93%9C%EA%B0%80-%EC%9D%B4%EC%A0%95%EB%8F%84%EB%8A%94-%ED%95%B4%EC%A4%98%EC%95%BC-%ED%95%A8-12.-%EC%96%B4%ED%94%8C%EB%A6%AC%EC%BC%80%EC%9D%B4%EC%85%98-%EB%A0%88%EB%B2%A8-%EC%9D%98%EC%82%AC%EA%B2%B0%EC%A0%95-2)

**Comment by hwangdaesun** [comment]
좋습니다! 최종 반영하겠습니다
